# Generated by Django 5.1.3 on 2024-11-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_delete_carros'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
