# Generated by Django 5.1.3 on 2024-11-22 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carros', '0004_delete_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=200)),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True)),
                ('modelo_ano', models.IntegerField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Carro_Marca', to='carros.marca')),
            ],
        ),
    ]
