# Generated by Django 5.1.3 on 2024-11-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carros',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
