# Generated by Django 5.1.3 on 2024-11-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='carros/'),
        ),
        migrations.AddField(
            model_name='carro',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
