# Generated by Django 5.1.3 on 2024-11-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0008_carro_foto_carro_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarroInventorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carros_quantidade', models.IntegerField()),
                ('carros_valor', models.FloatField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_registro'],
            },
        ),
    ]
