# Generated by Django 5.1.3 on 2024-11-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0009_carroinventorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
